name: isoworker
description: This is an easy to use wrapping of the Isolate class to make it easier to write parallel processes.
version: 1.0.0
homepage: https://github.com/zuvola/isoworker

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
