name: isoworker
description: This is an easy to use wrapping of the Isolate class to make it easier to write parallel processes.
version: 1.1.1
homepage: https://github.com/zuvola/isoworker

environment:
  sdk: ">=2.16.2 <4.0.0"

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
